/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejemplomenu;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Ismael Ruiz
 */
public class MenuPrincipal extends javax.swing.JFrame {

    int numero = 1;

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        btnArchivos.setIcon(definirIcono("/imagenes/icon_folder.png", btnArchivos));
        btnArchivos.setPressedIcon(efectoBoton("/imagenes/icon_folder.png", btnArchivos, 20, 20));//este
        btnReportes.setIcon(definirIcono("/imagenes/icon_graphics.png", btnReportes));
        btnReportes.setPressedIcon(efectoBoton("/imagenes/icon_graphics.png", btnReportes, 10, 10));//este
        btnUsuarios.setIcon(definirIcono("/imagenes/icon_login.png", btnUsuarios));
        btnUsuarios.setPressedIcon(efectoBoton("/imagenes/icon_login.png", btnUsuarios, 10, 10));//este
        btnArreglo.setIcon(definirIcono("/imagenes/icon_array.png", btnArreglo));
        btnArreglo.setPressedIcon(efectoBoton("/imagenes/icon_array.png", btnArreglo, 10, 10));//este
        btnMatriz.setIcon(definirIcono("/imagenes/icon_matriz.png", btnMatriz));
        btnMatriz.setPressedIcon(efectoBoton("/imagenes/icon_matriz.png", btnMatriz, 10, 10));//este
        btnAgenda.setIcon(definirIcono("/imagenes/icon_agenda.png", btnAgenda));
        btnAgenda.setPressedIcon(efectoBoton("/imagenes/icon_agenda.png", btnAgenda, 10, 10));//este
    }

    /**
     * Metodo que define el icono para los botones
     *
     * @param path
     * @param boton
     * @return
     */
    public final Icon definirIcono(String path, JButton boton) {
        ImageIcon icono = new ImageIcon(getClass().getResource(path));//Instanciamos un objeto de tipo ImageIcon
        int ancho = boton.getWidth();//Define el ancho de la imagen en funcion del ancho del boton
        int alto = boton.getHeight();//Define el alto de la imagen en funcion del alto del boton
        ImageIcon iconoDevuelto = new ImageIcon(icono.getImage().getScaledInstance(ancho, alto, Image.SCALE_DEFAULT));
        return iconoDevuelto;
    }

    /**
     * Metodo que crea el efecto al dar clic al boton
     *
     * @param path
     * @param boton
     * @param ancho
     * @param alto
     * @return
     */
    public final Icon efectoBoton(String path, JButton boton, int ancho, int alto) {
        ImageIcon icono = new ImageIcon(getClass().getResource(path));
        int width = boton.getWidth() - ancho;
        int heigth = boton.getHeight() - alto;
        ImageIcon iconoDevuelto = new ImageIcon(icono.getImage().getScaledInstance(width, heigth, Image.SCALE_DEFAULT));
        return iconoDevuelto;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnArchivos = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnArreglo = new javax.swing.JButton();
        btnMatriz = new javax.swing.JButton();
        btnAgenda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnArchivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clicArchivos(evt);
            }
        });

        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clicReportes(evt);
            }
        });

        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clicUsuarios(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MENU PRINCIPAL");

        jButton1.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 102));
        jButton1.setText("Salir del sistema");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnArreglo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArregloclicUsuarios(evt);
            }
        });

        btnMatriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatrizclicUsuarios(evt);
            }
        });

        btnAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendaclicUsuarios(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnArchivos, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnArreglo, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnReportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnArchivos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUsuarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnArreglo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clicArchivos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clicArchivos
        JOptionPane.showMessageDialog(null, "Soy el boton de archivos");
    }//GEN-LAST:event_clicArchivos

    private void clicReportes(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clicReportes
        JOptionPane.showMessageDialog(null, "Soy el boton de reportes");
    }//GEN-LAST:event_clicReportes

    private void clicUsuarios(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clicUsuarios
        JOptionPane.showMessageDialog(null, "Soy el boton de usuarios");
    }//GEN-LAST:event_clicUsuarios

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Login login = new Login();
        login.setLocationRelativeTo(null);
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnArregloclicUsuarios(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArregloclicUsuarios
        String nombres[] = new String[10];
        for (int i = 0; i < nombres.length; i++) {
            nombres[i] = JOptionPane.showInputDialog("Ingrese un nombre");
        }
        JOptionPane.showMessageDialog(null, nombres);
    }//GEN-LAST:event_btnArregloclicUsuarios

    private void btnMatrizclicUsuarios(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatrizclicUsuarios
        String nombres[][] = new String[2][3];
        for (int i = 0; i < 2; i++) {
            for (int j = 0; j < 3; j++) {
                nombres[i][j] = JOptionPane.showInputDialog("Ingrese un equipo");
            }
        }
        String cadena = "";
        for (int i = 0; i < 2; i++) {
            for (int j = 0; j < 3; j++) {
                cadena += nombres[i][j] + " ";
            }
            cadena += "\n";
        }
        JOptionPane.showMessageDialog(null, cadena);
    }//GEN-LAST:event_btnMatrizclicUsuarios

    private void btnAgendaclicUsuarios(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendaclicUsuarios
        Agenda agenda = new Agenda();
        this.setVisible(false);
        agenda.setLocationRelativeTo(null);
        agenda.setVisible(true);
    }//GEN-LAST:event_btnAgendaclicUsuarios

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgenda;
    private javax.swing.JButton btnArchivos;
    private javax.swing.JButton btnArreglo;
    private javax.swing.JButton btnMatriz;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
